// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/JMSException:1.0
//
/***/

final public class JMSException extends org.omg.CORBA.UserException
{
    private static final String _ob_id = "IDL:org.exolab.jms/org/exolab/jms/jobserver/JMSException:1.0";

    public
    JMSException()
    {
        super(_ob_id);
    }

    public
    JMSException(String _reason)
    {
        super(_ob_id + " " + _reason);
    }
}
