// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/MessageData:1.0
//
final public class MessageDataHolder implements org.omg.CORBA.portable.Streamable
{
    public MessageData value;

    public
    MessageDataHolder()
    {
    }

    public
    MessageDataHolder(MessageData initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = MessageDataHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        MessageDataHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return MessageDataHelper.type();
    }
}
