// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnectionFactory:1.0
//
/***/

public interface ServerConnectionFactoryOperations
{
    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnectionFactory/createConnection:1.0
    //
    /***/

    ServerConnection
    createConnection(String clientID,
                     String userName,
                     String password);
}
