// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession:1.0
//
final public class ServerSessionHolder implements org.omg.CORBA.portable.Streamable
{
    public ServerSession value;

    public
    ServerSessionHolder()
    {
    }

    public
    ServerSessionHolder(ServerSession initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ServerSessionHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ServerSessionHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ServerSessionHelper.type();
    }
}
