// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection:1.0
//
/***/

public interface ServerConnection extends ServerConnectionOperations,
                                          org.omg.CORBA.Object,
                                          org.omg.CORBA.portable.IDLEntity
{
}
