// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection:1.0
//
/***/

public interface ServerConnectionOperations
{
    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection/getConnectionId:1.0
    //
    /***/

    long
    getConnectionId();

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection/getClientID:1.0
    //
    /***/

    String
    getClientID();

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection/setClientID:1.0
    //
    /***/

    void
    setClientID(String clientID);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection/createSession:1.0
    //
    /***/

    ServerSession
    createSession(int acknowledgeMode,
                  boolean transacted);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnection/close:1.0
    //
    /***/

    void
    close();
}
