// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerConnectionFactory:1.0
//
final public class ServerConnectionFactoryHolder implements org.omg.CORBA.portable.Streamable
{
    public ServerConnectionFactory value;

    public
    ServerConnectionFactoryHolder()
    {
    }

    public
    ServerConnectionFactoryHolder(ServerConnectionFactory initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ServerConnectionFactoryHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ServerConnectionFactoryHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ServerConnectionFactoryHelper.type();
    }
}
