// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package org.exolab.jms.jobserver;

//
// IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession:1.0
//
/***/

public interface ServerSessionOperations
{
    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/close:1.0
    //
    /***/

    void
    close();

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/acknowledgeMessage:1.0
    //
    /***/

    void
    acknowledgeMessage(long consumerId,
                       String messageId);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/send:1.0
    //
    /***/

    void
    send(MessageData message);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/receiveNoWait:1.0
    //
    /***/

    MessageData
    receiveNoWait(long consumerId);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/receive:1.0
    //
    /***/

    MessageData
    receive(long consumerId,
            long _wait);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/createConsumer:1.0
    //
    /***/

    long
    createConsumer(DestinationData destination,
                   String selector,
                   boolean noLocal);

    //
    // IDL:org.exolab.jms/org/exolab/jms/jobserver/ServerSession/closeConsumer:1.0
    //
    /***/

    void
    closeConsumer(long consumerId);
}
